# Alacritty Configuration. Self-explanatory
[window]
dynamic_title = false
padding = { x = 5, y = 5 }
dimensions = { columns = 80, lines = 24 }

[font]
normal = { family = "monospace", style = "Regular" }
bold = { family = "monospace", style = "Bold" }
italic = {family = "monospace", style = "Italic" }
bold_italic = { family = "monospace", style = "Bold Italic" }
size = 12

[selection]
save_to_clipboard = true

# Ensure colors follow this format.
# [colors.primary]
# [colors.normal]
# [colors.bright]
# [colors.dim]
