# ~/.bash_aliases

# Color and clearscreen aliases
alias ls='ls --color=auto --block-size=K'
alias ll='ls -l'
alias grep='grep --color'
alias cls='clear'

# Make some possibly destructive commands more interactive.
alias rm='rm -i'
alias mv='mv -i'
alias cp='cp -i'

# Modern Linux commands
alias open='xdg-open'
alias ncdu='ncdu --color off'
alias neofetch='fastfetch --config neofetch'
alias drives="df -HT | grep -E 'ext4|btrfs|vfat|fuse*' | sort"

